version: '3'
services:
  client:
    image: "tonymall/multi-client-10-14"
    men-limit: 128m
    hostname: client
  server:
    image: "tonymall/multi-server-10-14"
    men-limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
    worker:
      image: "tonymall/multi-worker-10-14"
      men-limit: 128m
      hostname: worker
      environment:
        - REDIS_HOST=$REDIS_HOST
        - REDIS_PORT=$REDIS_PORT
    nginx:
      image: "tonymall/multi-nginx-10-14"
      men-limit: 128m
      men-limit: 128m
      men-limit: 128m
      hostname: nginx
      ports:
        - "80:80"